-- New Migration
ALTER TABLE buildings MODIFY flat VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY floor TINYINT(4) NULL;
ALTER TABLE buildings MODIFY house VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY road VARCHAR(511) NULL;

ALTER TABLE buildings MODIFY area VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY village VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY post_office VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY post_code VARCHAR(255) NULL;

ALTER TABLE buildings MODIFY police_station VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY addr_union VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY upazila VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY district VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY division VARCHAR(255) NULL;
ALTER TABLE buildings MODIFY country VARCHAR(255) NULL;

ALTER TABLE buildings MODIFY latitude DOUBLE NULL;
ALTER TABLE buildings MODIFY longitude DOUBLE NULL;

